schema: ./schema.gql
documents: ./ui/src/queries/**/*.gql
extensions:
  codegen:
    generates:
      ui/src/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
        config:
          avoidOptionals: false
          skipTypename: true
          useTypeImports: true
        hooks:
          afterOneFileWrite:
            - eslint --fix
      ui/src/schema.json:
        plugins:
          - introspection
        config:
          minify: true
  endpoints:
    default:
      url: http://localhost:4000/v1/console
      headers:
        Authorization: Bearer ${API_TOKEN}
