schema: ./schema.gql
documents: ./ui/src/queries/**/*.gql
extensions:
  codegen:
    hooks:
      afterOneFileWrite:
        - eslint --fix
    generates:
      ui/src/graphql-operations.ts:
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
        config:
          avoidOptionals: false
          skipTypename: true
          useTypeImports: true
  endpoints:
    default:
      url: http://localhost:4000/v1/console
      headers:
        Authorization: Bearer ${API_TOKEN}
