mutation signIn($email: String!, $password: String!) {
  signIn(email: $email, password: $password) {
    token
  }
}

mutation signUp($email: String!, $password: String!) {
  signUp(email: $email, password: $password) {
    token
  }
}

query getProfile {
  getProfile {
    name
    email
  }
}
