mutation createCollection(
  $projectId: ID!
  $name: String!
  $permissions: [String!]
) {
  createCollection(
    projectId: $projectId
    name: $name
    permissions: $permissions
  ) {
    code
    success
    message
    collection {
      id
      name
      updatedDate
      permissions
    }
  }
}

mutation updateCollection($id: ID!, $name: String, $permissions: [String!]) {
  updateCollection(collectionId: $id, name: $name, permissions: $permissions) {
    code
    success
    message
    collection {
      id
      name
      updatedDate
      permissions
    }
  }
}

mutation deleteCollection($id: ID!) {
  deleteCollection(id: $id) {
    code
    success
    message
  }
}

mutation createAttribute(
  $collectionId: ID!
  $name: String!
  $type: AttributeType!
) {
  createAttribute(collectionId: $collectionId, name: $name, type: $type) {
    code
    success
    message
    attribute {
      id
      name
      type
    }
    project {
      id
    }
  }
}

mutation deleteAttribute($id: ID!) {
  deleteAttribute(id: $id) {
    code
    success
    message
  }
}

mutation createManyToOneRelationship(
  $collectionId: ID!
  $name: String!
  $relatedCollectionId: ID!
  $inverse: String
) {
  createManyToOneRelationship(
    collectionId: $collectionId
    name: $name
    relatedCollectionId: $relatedCollectionId
    inverse: $inverse
  ) {
    code
    success
    message
    relationship {
      id
      name
      type
      owner
      relatedCollection {
        id
        name
      }
    }
    project {
      id
    }
  }
}

mutation createOneToOneRelationship(
  $collectionId: ID!
  $name: String!
  $relatedCollectionId: ID!
  $inverse: String
) {
  createOneToOneRelationship(
    collectionId: $collectionId
    name: $name
    relatedCollectionId: $relatedCollectionId
    inverse: $inverse
  ) {
    code
    success
    message
    relationship {
      id
      name
      type
      owner
      relatedCollection {
        id
        name
      }
    }
    project {
      id
    }
  }
}

mutation deleteRelationship($id: ID!) {
  deleteRelationship(id: $id) {
    code
    success
    message
  }
}
