mutation createCollection($projectId: ID!, $name: String!) {
  createCollection(projectId: $projectId, name: $name) {
    id
    name
    createdDate
  }
}

mutation deleteCollection($id: ID!) {
  deleteCollection(id: $id) {
    id
  }
}

mutation createAttribute(
  $collectionId: ID!
  $name: String!
  $type: AttributeType!
) {
  createAttribute(collectionId: $collectionId, name: $name, type: $type) {
    id
    name
    type
    projectId
  }
}

mutation deleteAttribute($id: ID!) {
  deleteAttribute(id: $id) {
    id
  }
}

mutation createManyToOneRelationship(
  $collectionId: ID!
  $name: String!
  $relatedCollectionId: ID!
  $inverse: String
) {
  createManyToOneRelationship(
    collectionId: $collectionId
    name: $name
    relatedCollectionId: $relatedCollectionId
    inverse: $inverse
  ) {
    id
    name
    type
    owner
    relatedCollection {
      id
      name
    }
    projectId
  }
}

mutation createOneToOneRelationship(
  $collectionId: ID!
  $name: String!
  $relatedCollectionId: ID!
  $inverse: String
) {
  createOneToOneRelationship(
    collectionId: $collectionId
    name: $name
    relatedCollectionId: $relatedCollectionId
    inverse: $inverse
  ) {
    id
    name
    type
    owner
    relatedCollection {
      id
      name
    }
    projectId
  }
}

mutation deleteRelationship($id: ID!) {
  deleteRelationship(id: $id) {
    id
  }
}
