mutation createKey($projectId: ID!, $name: String!, $scope: [Scope!]!) {
  createKey(projectId: $projectId, name: $name, scope: $scope) {
    id
    name
    scope
    createdDate
  }
}

mutation updateKey($id: ID!, $name: String, $scope: [Scope!]) {
  updateKey(id: $id, name: $name, scope: $scope) {
    id
    name
    scope
  }
}
mutation deleteKey($id: ID!) {
  deleteKey(id: $id) {
    id
  }
}
