mutation createUser(
  $projectId: ID!
  $email: String!
  $password: String!
  $name: String
) {
  createUser(
    projectId: $projectId
    email: $email
    password: $password
    name: $name
  ) {
    id
    name
    email
    createdDate
  }
}

mutation deleteUser($id: ID!) {
  deleteUser(id: $id) {
    id
  }
}
